import Footer from "@/Components/Footer/page";
import Navbar from "@/Components/Navbar/page";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

type Props = {
  children: React.ReactNode;
};

export default function layoutMain({ children }: Props) {
  return (
    <>
        <Navbar />
        <div>{children}</div>
        <Footer/>
    </>
  );
}
